Makefile: Disable stack protector
Some compilers have stack protector enabled by default (such as Bootlin
toolchains), causing compilation to fail with:

regmap.c:67:(.text.regmap_update_bits+0x8): undefined reference to
`__stack_chk_guard'
regmap.c:76:(.text.regmap_update_bits+0x90): undefined reference to
`__stack_chk_fail'

Since the hardware doesn't have memory protection capability, we can
safely disable it.

Signed-off-by: Dang Huynh <danct12@riseup.net>